### ISSUE TITLE
Is there a difference between Compseed's built-in bwamem and the official website?

### ISSUE THREAD

**Issue by MGI-fuqian** [i-xiaohu/CompSeed#1]
Hi！
First of all thank you for sharing this tool: Compseed
I am curious, is the "bwamem" encapsulated in Compeseed exactly the same as on the official website? Or did you make some changes?

**Comment by i-xiaohu** [comment]
Yes, the BWA-MEM code built in CompSeed is exactly the same as the official release version 0.7.17-r1188. 
It means when the input reads are identical, they produce the same alignment results.
The only change I made is to include the SST structure, which captures the repetitive seeds or calculations of BWA-MEM but doesn't affect the result.
